### ISSUE TITLE
v 3.1.1 The game is not saved

### ISSUE THREAD

**Issue by collagen12** [brandosha/gameplaycolor#2]
Even if you save the game, the previous save file is loaded. I can export the save file, but i can't import the save file. Perhaps this is related to the problem of not being able to save.

**Comment by brandosha** [comment]
Do you mean that if you import a save file the import doesn’t work or is it an issue with not resuming from the save after you close and reopen the app

**Comment by farmerryan** [comment]
Having the same issue. Save game, close app, restart, and it loads the previous save file. Uploading game state has no effect either.

**Comment by collagen12** [comment]
> Do you mean that if you import a save file the import doesn’t work or is it an issue with not resuming from the save after you close and reopen the app

both.

import doesn't work, also can't resuming from the save after you close and reopen the app

**Comment by brandosha** [comment]
The only way to fix the issue with not saving after closing and reopening the app is to delete all of the save data. The only way to do that right now is to delete and reinstall the app but I will add a button to clear save data soon because this seems to be affecting a lot of people

**Comment by collagen12** [comment]
> The only way to fix the issue with not saving after closing and reopening the app is to delete all of the save data. The only way to do that right now is to delete and reinstall the app but I will add a button to clear save data soon because this seems to be affecting a lot of people

Yeah! It's work! The saved file was properly stored in Google Drive and I was able to recover it. Also importing .sav files worked fine. Thank you for your kind help. :D
