### ISSUE TITLE
iPadOS 13 incompatible

### ISSUE THREAD

**Issue by iOS-Tutorials-Central** [brandosha/gameplaycolor#4]
On iPadOS 13, saving the page to the home screen works fine, however loading the GamePlay Color app from the home screen shows the same page in safari, meaning you can’t sign into google drive and therefore cannot play games on iPad 
![IMG_4588](https://user-images.githubusercontent.com/34008993/71754670-0d795080-2e7f-11ea-8136-9713f9c64aa6.png)

**Comment by brandosha** [comment]
You need to open the website in Safari and change the website preferences to use mobile. iPadOS defaults to the desktop version of websites.
