### ISSUE TITLE
Storage Crash / Native sav question

### ISSUE THREAD

**Issue by Kelescope** [brandosha/gameplaycolor#5]
Hi! Just wanted to ask about the native save files in GPC. I have successfully been able to export and import saves between my desktop and mobile (so awesome, thank you!) But I am still experiencing the "storage crash" from issue103 upon long plays, so it is hard to tell what has been accurately saved and where/when. Thus, I have been spamming all the save features. Should I save in a certain order, avoid certain save features, or anything else I could do to reduce this error? Also, I do have to relaunch every time I want to export, otherwise getting a white screen. Thanks again!

**Comment by brandosha** [comment]
I recently discovered that this might be an issue. If you close the app there is some bug with PWAs that closes the connection to the database meaning that new saves aren't stored properly. The only workaround I can see right now is relaunching the app every time you return from it being in the background.

**Comment by brandosha** [comment]
The snapshot save should somewhat help with this but it is triggered by the Page Visibility API which isn't always reliable

**Comment by Kelescope** [comment]
Just to clarify since I'm not too savvy, anytime you would tab out or lock
the phone, none of the save functions would work? As in it could still go
offline and come back on to sync as long as it doesn't lose focus, but
losing focus disrupts even the engagement with the local save file despite
the emulator running? Thanks again for explaining this all to me! Hope you
have a good day!

**Comment by brandosha** [comment]
Yes, due to some problem with the OS the connection to the local save data is closed when the app loses focus. The only way I can find to reconnect is to reload the page so I am currently working on a fix that will automatically reload without losing any data.

**Comment by Kelescope** [comment]
Awesome thanks! Do you have a donation page or personal plug you would like
shared when I reference this awesome app!? I know some parts of this
community can't really advertise/profit, so I like to help via word of
mouth if I can.

**Comment by brandosha** [comment]
@Kelescope Thanks for the offer, but I don't have anything like that. Plus all I did was add some small enhancements to the larger gameplaycolor project 🙂

**Comment by Kelescope** [comment]
Hey! Got 3.2.1 and sent a crash error, just wanted to give more data if you
needed. I can successfully log back into account and following a fresh wipe
I can get the title screen but presume I would have to resign every time I
imported. The "all buttons" seemed to successfully restart pokemon tcg game
after import, but still neither that or restart work on pokemon red to get
to title screen. Let me know if I can test anything else for you, thanks!

**Comment by brandosha** [comment]
I am currently working on a fix for the restart issue. I was hoping to get it out sooner but discovered another issue that I needed to fix as well.

**Comment by brandosha** [comment]
Just pushed out the new update.

**Comment by Kelescope** [comment]
Woo! You rock! Perfect timing too, I barely survived that f ing bellsprout
in the rock tunnel 😎🍻
