### ISSUE TITLE
Intermittent unresponsive screen

### ISSUE THREAD

**Issue by robios** [brandosha/gameplaycolor#6]
While playing a game, the screen becomes unresponsive. Only way to fix the issue is to quit to home and come back. Tested on iPadOS 13.5.1 (iPad mini 5).

**Comment by brandosha** [comment]
If I understand correctly all of the UI is still visible but you just can't use any of the controls?
Is it just random or have you noticed some pattern that causes the issue? That would help me reproduce the problem.

**Comment by brandosha** [comment]
Another question, is there a certain game that seems to cause the problem or does it happen for different games?

**Comment by robios** [comment]
Yes, the UI is still visible but all the controls are not responding. The game is not freezing. At a moment it seems random, but let me collect little more statistics. For the second question, I am playing only one game now so I am not sure.

**Comment by robios** [comment]
It's been running quite smoothly in the past week. Since it's not reproducible anymore, I am closing this issue. Sorry for  bothering.

**Comment by brandosha** [comment]
No problem
