### ISSUE TITLE
Offline not working in 14.5.1

### ISSUE THREAD

**Issue by rleez** [brandosha/gameplaycolor#8]
Offline mode is a bit wonky in 14.5.1 (and [maybe](https://www.reddit.com/r/PWA/comments/mipuso/offline_pwas_broken_in_iosipados_145_beta_6/) the 14.6 beta). If I open GPC3.3.2 while on airplane mode or no signal/wifi, I get the 'Safari cannot open the page because your iPhone is not connected to the internet' error most of the time with no option to bypass or relaunch. Occasionally, it will work and load properly. 

Obviously the save/load state feature won't work when offline, but the intermittent inability to use the core functions while offline seems to be related to your build. The 3.0.2 (GPC.com) version has no issues running while offline. Is it an issue you're aware of and related to the save/load feature? Or is it possibly an iOS bug?

Thanks!

**Comment by brandosha** [comment]
I haven’t updated to 14.5.1 yet on my device and it appears to be working fine so it is likely an iOS issue. I’ll see if there is anything I can do about it though.

Maybe the other GPC is working because it is still using the application cache.

**Comment by rleez** [comment]
You're probably correct about the app cache. It's not a huge issue, just noticed it after being without a signal for a few hours last week and not being able to kill time with GPC! No problems since and seems you can get around it by opening the app when connected and not force closing it.

Has there been any progress on merging some of your features with the main devs? 

Thanks for the quick response!

**Comment by brandosha** [comment]
There was a little bit of communication with the main developer and I think it’s pretty much ready to merge but for right now I’m just waiting.
